import './globals.css'
import Providers from './providers'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="  bg-[#E8E6E2] dark:bg-[#202328]">
        <Providers>
    
        {children}
        </Providers>
       
        </body>

    </html>
  )
}
